protected/modules/user/models/User.php
<?php

class User extends CActiveRecord
{
	const STATUS_NOACTIVE=0;
	const STATUS_ACTIVE=1;
	const STATUS_BANED=-1;
	
	/**
	 * The followings are the available columns in table 'users':
	 * @var integer $id
	 * @var string $username
	 * @var string $password
	 * @var string $email
	 * @var string $phone
	 * @var string $activkey
	 * @var integer $createtime
	 * @var integer $lastvisit
	 * @var integer $superuser
	 * @var integer $status
	 * @var string $quests
	 * @var string $locations
	 * @var string $city_id
	 */

	/**
	 * Returns the static model of the specified AR class.
	 * @return CActiveRecord the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return Yii::app()->getModule('user')->tableUsers;
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
	
		return ((Yii::app()->getModule('user')->isAdmin()) ? 
			array(
				array('username, email, phone', 'required'),
				array('username', 'length', 'max'=>20, 'min' => 3,'message' => UserModule::t("Incorrect username (length between 3 and 20 characters).")),
				array('phone', 'length', 'max'=>18, 'min' => 5,'message' => UserModule::t("Incorrect phone (length between 5 and 12 characters).")),
				array('password', 'length', 'max'=>128, 'min' => 4,'message' => UserModule::t("Incorrect password (minimal length 4 symbols).")),
				array('email', 'email'),
				array('email', 'unique', 'message' => UserModule::t("This user's email address already exists.")),
				array('status', 'in', 'range'=>array(self::STATUS_NOACTIVE,self::STATUS_ACTIVE,self::STATUS_BANED)),
				array('superuser', 'in', 'range'=>array(0,1,2,3)),
				array('username, email, createtime, lastvisit, superuser, status', 'required'),
				array('createtime, lastvisit, superuser, status', 'numerical', 'integerOnly'=>true),
				array('username, email, phone', 'safe', 'on'=>'search'),
			)
			:
			(
				(Yii::app()->user->id==$this->id) ? 

				array(
					array('username, email, phone', 'required'),
					array('username', 'length', 'max'=>20, 'min' => 3,'message' => UserModule::t("Incorrect username (length between 3 and 20 characters).")),
					array('phone', 'length', 'max'=>18, 'min' => 5,'message' => UserModule::t("Incorrect phone (length between 5 and 12 characters).")),
					array('email', 'email'),
					array('email', 'unique', 'message' => UserModule::t("This user's email address already exists.")),

				) : array()
			));
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		$relations = array();
		if (isset(Yii::app()->getModule('user')->relations))
			$relations = array_merge($relations,Yii::app()->getModule('user')->relations);
		return $relations;
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'username'=>UserModule::t("username"),
			'name'=>UserModule::t("name"),
			'password'=>UserModule::t("password"),
			'verifyPassword'=>UserModule::t("Retype Password"),
			'email'=>UserModule::t("E-mail"),
			'verifyCode'=>UserModule::t("Verification Code"),
			'id' => UserModule::t("Id"),
			'activkey' => UserModule::t("activation key"),
			'createtime' => UserModule::t("Registration date"),
			'lastvisit' => UserModule::t("Last visit"),
			'phone' => UserModule::t("Phone"),
			'quests' => Yii::t('app','Quest'),
			'locations' => Yii::t('app','Locations'),
			'superuser' => 'Роль',
			'moderator' => 'Модератор',
			'city_id' => Yii::t('app','City'),
			'status' => UserModule::t("Status"),
		);
	}
	
	public function scopes()
    {
        return array(
            'active'=>array('condition'=>'status='.self::STATUS_ACTIVE),
            'notactvie'=>array('condition'=>'status='.self::STATUS_NOACTIVE),
            'banned'=>array('condition'=>'status='.self::STATUS_BANED),
            'superuser'=>array('condition'=>'superuser=1'),
            'admin'=>array('condition'=>'superuser=3'),
            'moderator'=>array('condition'=>'superuser=2'),
            'notsafe'=>array(
            	'select' => 'id, username, password, email, activkey, createtime, lastvisit, superuser, status',
            ),
        );
    }
	
	public function defaultScope() {
        return array(
            'select' => 'id, username, email, phone, createtime, lastvisit, superuser, status, quests, locations, fb_link, fb_id, vk_id, city_id',
        );
    }

    public static function listQuests($quests) {
		$titles = array();
    	foreach ($quests as $q) {
			array_push($titles, $q->title);
		}
		return implode(', ', $titles);
	}

    public static function listLocations($locations) {
		$names = array();
    	foreach ($locations as $l) {
			array_push($names, $l->name);
		}
		return implode(', ', $names);
	}
	
	public static function itemAlias($type,$code=NULL) {
		$_items = array(
			'UserStatus' => array(
				self::STATUS_NOACTIVE => UserModule::t('Not active'),
				self::STATUS_ACTIVE => UserModule::t('Active'),
				self::STATUS_BANED => UserModule::t('Banned'),
			),
			'AdminStatus' => array(
				'0' => UserModule::t('Пользователь'),
				'1' => UserModule::t('Суперадмин'),
				'2' => UserModule::t('Модератор квеста'),
				'3' => UserModule::t('Модератор'),
			),
		);
		if (isset($code))
			return isset($_items[$type][$code]) ? $_items[$type][$code] : false;
		else
			return isset($_items[$type]) ? $_items[$type] : false;
	}

	/**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.
        $criteria=new CDbCriteria;
        
        $criteria->compare('id',$this->id, true);
        $criteria->compare('username',$this->username,true);
        $criteria->compare('email',$this->email,true);
        $criteria->compare('phone',$this->phone,true);
        $criteria->compare('superuser',$this->superuser);
        $criteria->compare('status',$this->status);
        return new CActiveDataProvider(get_class($this), array(
            'criteria'=>$criteria,
        	'pagination'=>array(
				'pageSize'=>Yii::app()->getModule('user')->user_page_size,
			),
        ));
    }

}

protected/modules/user/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	public $layout = '//layouts/main';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return CMap::mergeArray(parent::filters(),array(
			'accessControl', // perform access control for CRUD operations
		));
	}
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow',
				'actions'=>array('list', 'export', 'exportlab'),
				'expression'=>"Yii::app()->getModule('user')->user()->superuser > 0",
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}	

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
	
		$this->layout = "//layouts/admin";
		$model = $this->loadModel();
		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{

		// var_dump($this->layout); die;
		$this->layout = "//layouts/admin";

		$dataProvider=new CActiveDataProvider('User', array(
			'criteria'=>array(
		        'condition'=>'status>'.User::STATUS_BANED,
		    ),
				
			'pagination'=>array(
				'pageSize'=>Yii::app()->controller->module->user_page_size,
			),
		));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=User::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the primary key value. Defaults to null, meaning using the 'id' GET variable
	 */
	public function loadUser($id=null)
	{
		if($this->_model===null)
		{
			if($id!==null || isset($_GET['id']))
				$this->_model=User::model()->findbyPk($id!==null ? $id : $_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

	public function actionList()
	{
		if(Yii::app()->request->isAjaxRequest){

			$this->layout=false;
			header('Content-type: application/json');

			$val = addcslashes($_GET['val'], '%_'); // escape LIKE's special characters
			$q = new CDbCriteria( array(
			    'condition' => "(username LIKE :val OR email LIKE :val OR phone LIKE :val) AND superuser = 0",         // no quotes around :match
			    'params'    => array(':val' => "%$val%")  // Aha! Wildcards go here
			) );

			$users = User::model()->findALL($q);

			echo CJavaScript::jsonEncode(
				array(
					'success'=>1,
					'data'=>$users,
				)
			);
		} else echo CJavaScript::jsonEncode(array('success'=>0, 'message'=> 'Неправильный запрос'));
	}

	public function actionExport()
	{
		$this->layout=false;
		header("Content-type: text/csv");
		header("Content-Disposition: attachment; filename=export_user.csv");
		header("Pragma: no-cache");
		header("Expires: 0");

		$users = User::model()->findALL(array("condition"=>"superuser = 0"));

		foreach ($users as $user) {
			echo $user->username.','.$user->email.','.$user->phone."\r\n";
		}
		die;
	}

	public function actionExportLab()
	{
		$this->layout=false;
		header("Content-type: text/csv");
		header("Content-Disposition: attachment; filename=export_wlab_user.csv");
		header("Pragma: no-cache");
		header("Expires: 0");

		$sql = "SELECT DISTINCT(competitor_id) FROM tbl_booking WHERE quest_id = 4;";
    	$list = Yii::app()->db->createCommand($sql)->queryAll();
    	$func = function($value) {
			return $value['competitor_id'];
		};

		$b = array_map($func, $list);
    	$ids = implode(",", $b);
    	$sql = "SELECT * FROM tbl_users WHERE superuser=0 AND id NOT IN (".$ids.") ;";
		$users = Yii::app()->db->createCommand($sql)->queryAll();
		// var_dump($users); die;
    	foreach ($users as $user) {
			echo $user['id'].','.$user['username'].','.$user['email'].','.$user['phone']."\r\n";
		}
		die;
	}
}

protected/modules/user/views/user/index.php

<h1><?php echo UserModule::t("List User"); ?></h1>
<?php if(UserModule::isAdmin()) {
	?><ul class="actions">
	<li><?php echo CHtml::link(UserModule::t('Manage User'),array('/user/admin')); ?></li>
</ul><!-- actions --><?php 
} ?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'=>$dataProvider,
	'columns'=>array(
		array(
			'name' => 'username',
			'type'=>'raw',
			'value' => 'CHtml::link(CHtml::encode($data->username),array("user/view","id"=>$data->id))',
		),
		array(
			'name' => 'createtime',
			'value' => 'date("d.m.Y H:i:s",$data->createtime)',
		),
		array(
			'name' => 'lastvisit',
			'value' => '(($data->lastvisit)?date("d.m.Y H:i:s",$data->lastvisit):UserModule::t("Not visited"))',
		),
	),
)); ?>

protected/modules/user/views/user/login.php
<?
 $this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Login");
?>
<div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
          <div id="myModalAuth" class="login-page">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <a class="h4 modal-title active" data-toggle="tab" href="#auth" id="auth-tab" role="tab"><?=Yii::t('app','Sign in')?></a>
                  <a class="h4 modal-title" data-toggle="tab" href="#reg" role="tab"><?=Yii::t('app','Check In')?></a>
                  <hr class="fadeOut">
                </div>
                <div class="modal-body">
                  <div class="row social_auth">
                    <div class="col-xs-6 text-right">
                      <a class="vk" href="https://oauth.vk.com/authorize?client_id=4659293&scope=uid,first_name,last_name,sex,bdate,email&redirect_uri=http://<?=$_SERVER['SERVER_NAME']; ?>/user/login/vkauth&response_type=code"></a>
                    </div>
                    <div class="col-xs-6 text-left">
                      <? if ($_SERVER['HTTP_HOST'] != 'cq.il' && $_SERVER['HTTP_HOST'] != 'cq.kzil') { ?>
                        <script>
                          function statusChangeCallback(response) {
                            if (response.status === 'connected' && $.cookie("logout") != 1) goAuth();
                          }

                          function checkLoginState() {
                            FB.getLoginStatus(function(response) {
                              statusChangeCallback(response);
                            });
                          }

                          window.fbAsyncInit = function() {
                            FB.init({
                              appId      : '748253021885085',
                              cookie     : true,
                              xfbml      : true,
                              version    : 'v2.1'
                            });

                            FB.getLoginStatus(function(response) {
                              statusChangeCallback(response);
                            });

                          };

                          (function(d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0];
                            if (d.getElementById(id)) return;
                            js = d.createElement(s); js.id = id;
                            js.src = "//connect.facebook.net/en_US/sdk.js";
                            fjs.parentNode.insertBefore(js, fjs);
                          }(document, 'script', 'facebook-jssdk'));

                          function goAuth() {
                            FB.api('/me', function(response) {
                              $.post(
                                "/user/login/fbauth",
                                response,
                                function(data){
                                  try {
                                    var data = JSON.parse(data);
                                    if (data && data.auth && data.auth == 1){
                                      location.reload();
                                    }
                                  } catch (e) {
                                    console.log(e);
                                  }
                              });
                            });
                          }

                          function loginFb(){
                            $.cookie('logout',0);
                            FB.login(function(response) {
                              checkLoginState();
                            }, {scope: 'email, public_profile'});
                          }
                        </script>
                      <? } ?>
                      <div id="fb_logincustom_btn" onclick="loginFb();"></div>
                    </div>
                    <div class="col-xs-12">
                      <div class="orTbl">
                        <div class="orRow">
                          <div class="orCell orL"></div>
                          <div class="orCell orC">
                            <span><?=Yii::t('app','or'); ?></span>
                          </div>
                          <div class="orCell orR"></div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="tab-content" style="padding:0;">
                    <div class="tab-pane active" id="auth">
                      <form role="form" id="auth-form" action="">
                        <div class="form-group" id="form-group-username-auth">
                          <input class="form-control" placeholder="Email" id="auth-email" name="email" type="email">
                          <span class="error-msg">?</span>
                        </div>
                        <div class="form-group" style="display:none;" id="form-group-forgot-auth">
                          <input class="form-control" placeholder="Email" id="auth-forgot" type="forgot_email" name="email">
                          <div class="clearfix"></div>
                          <p class="help-block" style="margin-top: 45px;"><small style="font-size:12px;"><?=Yii::t('app','To recover a password, enter Email'); ?></small></p>
                          <span class="error-msg">?</span>
                        </div>
                        <div class="form-group" id="form-group-pass-auth">
                          <input class="form-control" placeholder="<?=Yii::t('app','Password'); ?>" id="auth-pass" name="Profile[password]" type="password">
                          <span class="error-msg">?</span>
                        </div>
                        <div class="checkbox forgot"><label id="forgot"><?=Yii::t('app','Forgot your password?')?></label><label style="display:none;" id="auth_toogl"><?=Yii::t('app','Log In')?></label></div>
                        <button class="btn btn-default btn-block btn-lg" type="submit" data-value="go"><?=Yii::t('app','LOGIN')?></button>
                      </form>
                    </div>
                    <div class="tab-pane" id="reg">
                      <form role="form" id="reg-form" action="">
                        <div class="form-group" id="form-group-reg-email">
                          <input required class="form-control" placeholder="Email" id="reg-email" name="email" type="email">
                          <span class="error-msg">?</span>
                        </div>
                        <div class="form-group" id="form-group-reg-name">
                          <input required class="form-control" placeholder="<?=Yii::t('app','Name')?>" id="reg-name" name="username" type="text">
                          <span class="error-msg">?</span>
                        </div>
                        <div class="form-group" id="form-group-reg-phone">
                          <input required class="form-control" placeholder="+7(___)-___-__-__" id="reg-phone" name="Profile[phone]" type="text">
                          <span class="error-msg">?</span>
                        </div>
                        <div class="form-group" id="form-group-reg-pass">
                          <input required class="form-control" placeholder="<?=Yii::t('app','Password')?>" type="password" id="reg-pass" name="Profile[password]">
                          <span class="error-msg">?</span>
                        </div>
                        <div class="checkbox invisible" style="margin: 0;height: 20px;">
                          <label><input type="checkbox" id="reg-rules"><?=Yii::t('app','I accept')?> <a href="/rules"><?=Yii::t('app','Terms of Use'); ?></a></label>
                        </div>
                        <button class="btn btn-default btn-block btn-lg" type="submit"><?=Yii::t('app','Sign Up')?></button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
</div>

protected/modules/user/views/user/message.php
<?php $this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Login"); ?>


<div class="container">
	<div class="row rules">
		<div class="col-xs-10 col-xs-offset-1 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2 text-center">
			<h3 class=""><?php echo $title; ?></h3>
			<?php echo $content; ?>
		</div>
	</div>
</div>

protected/modules/user/views/user/registration.php
<?php $this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Registration");
$this->breadcrumbs=array(
	UserModule::t("Registration"),
);
?>

<h1><?php echo UserModule::t("Registration"); ?></h1>

<?php if(Yii::app()->user->hasFlash('registration')): ?>
<div class="success">
<?php echo Yii::app()->user->getFlash('registration'); ?>
</div>
<?php else: ?>

<div class="form">
<?php $form=$this->beginWidget('UActiveForm', array(
	'id'=>'registration-form',
	'enableAjaxValidation'=>true,
	'disableAjaxValidationAttributes'=>array('RegistrationForm_verifyCode'),
	'htmlOptions' => array('enctype'=>'multipart/form-data'),
)); ?>

	<p class="note"><?php echo UserModule::t('Fields with <span class="required">*</span> are required.'); ?></p>
	
	<?php echo $form->errorSummary(array($model,$profile)); ?>
	
	<div class="row">
	<?php echo $form->labelEx($model,'username'); ?>
	<?php echo $form->textField($model,'username'); ?>
	<?php echo $form->error($model,'username'); ?>
	</div>
	
	<div class="row">
	<?php echo $form->labelEx($model,'password'); ?>
	<?php echo $form->passwordField($model,'password'); ?>
	<?php echo $form->error($model,'password'); ?>
	<p class="hint">
	<?php echo UserModule::t("Minimal password length 4 symbols."); ?>
	</p>
	</div>
	
	<div class="row">
	<?php echo $form->labelEx($model,'verifyPassword'); ?>
	<?php echo $form->passwordField($model,'verifyPassword'); ?>
	<?php echo $form->error($model,'verifyPassword'); ?>
	</div>
	
	<div class="row">
	<?php echo $form->labelEx($model,'email'); ?>
	<?php echo $form->textField($model,'email'); ?>
	<?php echo $form->error($model,'email'); ?>
	</div>
	
<?php 
		$profileFields=$profile->getFields();
		if ($profileFields) {
			foreach($profileFields as $field) {
			?>
	<div class="row">
		<?php echo $form->labelEx($profile,$field->varname); ?>
		<?php 
		if ($field->widgetEdit($profile)) {
			echo $field->widgetEdit($profile);
		} elseif ($field->range) {
			echo $form->dropDownList($profile,$field->varname,Profile::range($field->range));
		} elseif ($field->field_type=="TEXT") {
			echo$form->textArea($profile,$field->varname,array('rows'=>6, 'cols'=>50));
		} else {
			echo $form->textField($profile,$field->varname,array('size'=>60,'maxlength'=>(($field->field_size)?$field->field_size:255)));
		}
		 ?>
		<?php echo $form->error($profile,$field->varname); ?>
	</div>	
			<?php
			}
		}
?>
	<?php if (UserModule::doCaptcha('registration')): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		<?php echo $form->error($model,'verifyCode'); ?>
		
		<p class="hint"><?php echo UserModule::t("Please enter the letters as they are shown in the image above."); ?>
		<br/><?php echo UserModule::t("Letters are not case-sensitive."); ?></p>
	</div>
	<?php endif; ?>
	
	<div class="row submit">
		<?php echo CHtml::submitButton(UserModule::t("Register")); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->
<?php endif; ?>

protected/modules/user/views/user/view.php


<h1><?php echo UserModule::t('View User').' "'.$model->username.'"'; ?></h1>

<ul class="actions">
	<li><?php echo CHtml::link(UserModule::t('List User'),array('index')); ?></li>
</ul><!-- actions -->

<?php 

// For all users
	$attributes = array(
			'username',
	);
	
	array_push($attributes,
		array(
			'name' => 'createtime',
			'value' => date("d.m.Y H:i:s",$model->createtime),
		),
		array(
			'name' => 'lastvisit',
			'value' => (($model->lastvisit)?date("d.m.Y H:i:s",$model->lastvisit):UserModule::t('Not visited')),
		)
	);
			
	$this->widget('zii.widgets.CDetailView', array(
		'data'=>$model,
		'attributes'=>$attributes,
	));

?>